"""init schema bigint v3

Revision ID: 2e450ed98378
Revises: 
Create Date: 2025-04-28 20:13:26.752052

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e450ed98378'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('goals',
    sa.Column('goal_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('goal_category', sa.String(length=8), nullable=True),
    sa.Column('goal_subtype', sa.String(length=32), nullable=True),
    sa.Column('target_name', sa.String(length=128), nullable=True),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.Column('progress_pct', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('goal_id')
    )
    op.create_table('learning_styles',
    sa.Column('style_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('memorising', sa.Integer(), nullable=True),
    sa.Column('researching', sa.Integer(), nullable=True),
    sa.Column('practising', sa.Integer(), nullable=True),
    sa.Column('reading', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('style_id')
    )
    op.create_table('goal_tasks',
    sa.Column('task_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('goal_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('weight_pct', sa.BigInteger(), nullable=True),
    sa.Column('state', sa.String(length=16), nullable=True),
    sa.ForeignKeyConstraint(['goal_id'], ['goals.goal_id'], ),
    sa.PrimaryKeyConstraint('task_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('goal_tasks')
    op.drop_table('learning_styles')
    op.drop_table('goals')
    # ### end Alembic commands ###
