name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_DATABASE: growth
          MYSQL_USER: growth
          MYSQL_PASSWORD: growth
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306
        options: >-
          --health-cmd "mysqladmin ping --silent"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Poetry & project deps
        run: |
          pip install poetry
          poetry config virtualenvs.create false
          poetry install --no-interaction

      - name: Run tests (placeholder)
        env:
          DATABASE_URL: mysql+pymysql://growth:growth@localhost:3306/growth
        run: |
          pytest -q || echo "no tests yet"

